Begin dealing with syn submit issues

diff --git a/bin/synapse_submit b/bin/synapse_submit
--- a/bin/synapse_submit
+++ b/bin/synapse_submit
@@ -1,9 +1,23 @@
 #!/usr/bin/env bash
 set -euf -o pipefail
 
+while getopts ":t:" opt; do
+  case $opt in
+   	t) team="$OPTARG"
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
 # parse credentials from config file
-CREDENTIALS=($(python /usr/local/bin/parse_config.py ${1}))
+#CREDENTIALS=($(python /usr/local/bin/parse_config.py ${1}))
+#CREDENTIALS=($(python parse_config.py ${1}))
 
 # get file from Synapse
-synapse login -u ${CREDENTIALS[0]} -p ${CREDENTIALS[1]} --rememberMe
-synapse submit --evalID ${2} --team ${3} --file ${4} --parentId ${5} --entityId ${6}
+#synapse login -u ${CREDENTIALS[0]} -p ${CREDENTIALS[1]} --rememberMe
+echo $#
+echo "$team"
+#if [ "$#" == "5" ]
+#then
+#	synapse submit --evalID ${2} --team ${3} --file ${4} --parentId ${5}
+#fi
